# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: dotnet build -c Release
    displayName: 'Build'

  - script: dotnet publish -c Release --no-build
    displayName: 'Package'
    
  - publish: $(Build.SourcesDirectory)/src/SaturdayJazz.Host/bin/Release/netcoreapp5.0/publish
    artifact: 'Host'
    displayName: 'Publish Artefacts'
